[tool.poetry]
name = "socket"
version = "0.1.0"
description = ""
authors = ["shima004 <yellow030408@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
protobuf = "^4.24.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
